get method was called 2024-03-30 15:39:39.320492
Person data not valid 2024-03-30 15:44:42.972757
Bad Request: /person/
Not Found: /person/1/
Not Found: /person/1/
Not Found: /person/1/
Person updated with id 1 2024-03-30 15:58:59.358793
Person updated with id 1 2024-03-30 15:59:18.830492
Person data not valid 2024-03-30 15:59:34.643856
Bad Request: /person/1/
User 1 has been deleted
Internal Server Error: /person/1/
Traceback (most recent call last):
  File "C:\home\React\djnago_rest_framework\Final_project3_backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\home\React\djnago_rest_framework\Final_project3_backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\home\React\djnago_rest_framework\Final_project3_backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\home\React\djnago_rest_framework\Final_project3_backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\home\React\djnago_rest_framework\Final_project3_backend\venv\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\home\React\djnago_rest_framework\Final_project3_backend\venv\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
Not Found: /person/1/
User 2 has been deleted
get method was called 2024-03-30 16:36:05.375967
get method was called 2024-03-30 16:36:05.463731
get method was called 2024-03-30 16:36:06.076685
get method was called 2024-03-30 16:36:33.967503
get method was called 2024-03-30 16:37:02.177350
get method was called 2024-03-30 16:37:16.318458
get method was called 2024-03-30 16:37:16.320451
get method was called 2024-03-30 16:37:23.975437
get method was called 2024-03-30 16:37:28.615190
get method was called 2024-03-30 16:37:28.654086
get method was called 2024-03-30 16:46:13.504143
get method was called 2024-03-30 16:46:13.508033
get method was called 2024-03-30 16:46:39.952515
get method was called 2024-03-30 16:46:39.960932
get method was called 2024-03-30 16:47:09.503125
get method was called 2024-03-30 16:47:15.899996
get method was called 2024-03-30 16:47:25.541024
get method was called 2024-03-30 16:47:34.023728
get method was called 2024-03-30 16:47:41.121681
get method was called 2024-03-30 16:47:44.675019
get method was called 2024-03-30 16:47:51.303521
get method was called 2024-03-30 16:47:52.848016
get method was called 2024-03-30 16:48:36.185485
get method was called 2024-03-30 16:48:38.276158
get method was called 2024-03-30 16:48:47.126660
get method was called 2024-03-30 16:48:48.417260
get method was called 2024-03-30 16:48:59.125977
get method was called 2024-03-30 16:48:59.872691
get method was called 2024-03-30 16:49:06.133680
get method was called 2024-03-30 16:54:17.698758
Person updated with id 6 2024-03-30 16:54:17.703746
get method was called 2024-03-30 16:54:17.717727
get method was called 2024-03-30 16:55:31.552249
get method was called 2024-03-30 16:55:31.606404
get method was called 2024-03-30 16:55:44.236609
get method was called 2024-03-30 16:57:24.440431
get method was called 2024-03-30 16:57:24.452400
get method was called 2024-03-30 16:59:03.710497
User 8 has been deleted
get method was called 2024-03-30 16:59:03.738420
